---
- name: installing lamp on generic-os
  become: yes
  hosts: servers
  vars_files:
    defaults.yaml
  tasks:
    - name: "installing {{ package }}"
      ansible.builtin.package:
        name: "{{ package }}"
        state: present
    - name: "installing {{ package1 }}"
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ package1 }}"
    - name: "installing {{ package2 }}"
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ package2 }}"
    - name: copy file to php location
      ansible.builtin.copy:
        src: info.php
        dest: "{{ file_location }}"
      notify: "restarting {{ package }}"
  handlers:
    - name: "restarting {{ package }}"
      ansible.builtin.service:
        name: "{{ package }}"
        state: restarted
        enabled: yes
      when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "20") or (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "9")

