---
- name: installing lamp on rhel9
  become: yes
  hosts: appservers
  vars: 
    file_location: /var/www/html/
  tasks:
    - name: install httpd pkgs
      ansible.builtin.dnf:
        name: "{{ package }}"
        state: present
    - name: install php pkgs
      ansible.builtin.dnf:
        name: "{{ package1 }}"
        state: present
    - name: copy info.php file
      ansible.builtin.copy:
        src: info.php
        dest: "{{ file_location }}"
      notify: enable start httpd
  handlers:
    - name: enable start httpd
      ansible.builtin.service:
        name: "{{ package }}"
        enabled: yes
        state: restarted