---
- name: installing lamp on ubuntu
  become: yes
  hosts: webservers
  tasks:
    - name: installing apache and php pkgs
      ansible.builtin.apt:
        update_cache: yes
        name: "{{ package }}"
        state: present  
    - name: installing php pkgs
      ansible.bulitin.apt:
        name: "{{ package1 }}"
        state: present
    - name: copy file to php location
      ansible.builtin.copy:
        src: info.php
        dest: "{{ file_location }}"
      notify:
        - restarting apache server
  handlers:
    - name: restarting apache server
      ansible.builtin.service:
        name: "{{ package }}"
        state: restarted
      


